# -*- coding: utf-8 -*-
"""Wk_2_Assign_Alissa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XE2YzNE7BgKZaKG1Y_OWfJbBIkD80DQT

##Assignment 2 – Data Wrangling with pandas

#### Index, assign, groupby, aggregate, sort, logic, chaining
"""

import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 20)

dt = pd.read_csv(
    "https://raw.githubusercontent.com/Alissa-Ouspen/data201_alissa/refs/heads/main/datasets/housing.csv")
pd.options.display.float_format = '{:.2f}'.format
dt.head(10)

#dt.dropna(subset = ["size"])   # not needed

ds = (dt[(dt["price"] > 250000) & (dt["size"] > 1000)]
      .assign(ppsqft = dt["price"] / dt["size"])
      .groupby("neighborhood")    # must be grouped first
      .agg(
        mean_ppsqft = ("ppsqft", "mean"),
        median_ppsqft = ("ppsqft", "median"),
        count = ("ppsqft", "count")
      )
      .sort_values(by = ["neighborhood"], ascending = True)
)
ds